### PR TITLE
implement minikube class for cluster create/delete/modify/display

### PR DESCRIPTION
**Pull request by 312hzeng**

### CODE REVIEW

**Comment by tianyin** [comment]
WoW! This is an exciting feature!

**Comment by tianyin** [comment]
@312hzeng Let me know when you think you can merge it.

**Comment by 312hzeng** [comment]
> @312hzeng Let us know when you think you can merge it.

Thank you Professor Xu! I think I'll ask Tyler about his suggestions for the code revision regarding class method implementation and related testcases on tomorrow's meeting before this pr can get merged.

**Comment by tianyin** [comment]
great

btw how did you test your feature/PR? @312hzeng

**Comment by 312hzeng** [comment]
> great
> 
> btw how did you test your feature/PR? @312hzeng
Thank you for the question, I use pytest to test individual feature.
create cluster:
call the method and check them using `minikube profile list` for the version, name, num_nodes, etc
delete cluster:
call the method and check them using `minikube profile list`
display nodes in the cluster:
call create and then call the display method, assert the num_nodes
call delete and then call the display method, expect a runtime error is raised

I think there's more to add to the testcases, I just want to discuss the update with Tyler first tomorrow before I add more testing

**Comment by tylergu** [comment]
BTW the End-to-End Test runs on riverrun, which has been flaky recently. The End-to-End Test may fail due to timeout (24 hrs), I will run it on a cloudlab machine.

**Comment by 312hzeng** [comment]
ok, thank you for the information

**Review by tylergu — APPROVED** [review]

**Comment by tianyin** [comment]
WoW this is a big PR and is opened in Oct 9, 2023! Glad to see that it was not given up but finally merged. Great job @312hzeng and @tylergu !

**Pull request merged**
