### PR TITLE
Add files for the grafana operator. Also modify log parser.

### PR DESCRIPTION
**Pull request by chaseblock**
This adds the config files for testing the grafana-operator.

It also modifies the `parse_log.py` to make it compatible with the logging format that this operator uses.

### CODE REVIEW

**Comment by chaseblock** [comment]
@tylergu Just pinging to make sure you see that I updated this. Thanks.

**Comment by tylergu** [comment]
@chaseblock Thanks for considering adding this extra log parser! The PR looks good, just a small nit: could you name the regex as `grafana_logr_regex` instead?

Also, could you include the context.json generated by Acto too?

**Comment by chaseblock** [comment]
@tylergu Sure thing.

**Review by tylergu — APPROVED** [review]

**Comment by tylergu** [comment]
@chaseblock Thank you for contributing!

**Pull request merged**
