### PR TITLE
add CloudLab profile

### PR DESCRIPTION
**Pull request by whentojump**
- [x] For CloudLab to be able to fetch this file, it should be at the root of the default branch. But we probably don't want it to be in the `main` branch. A quick workaround is to let `sosp-ae` be the default branch during the AE process. Thoughts? @tylergu 
    - This is addressed by moving all CloudLab- and Ansible-related stuffs to a separate repo: https://github.com/xlab-uiuc/acto-cloudlab
- [x] I ran it last night. It turns out the startup script is run by the nonhuman user `geniuser`. So the tmpfs and cloned `acto` repository are now in `/users/geniuser`. I'm figuring out the solution.
    - See [comment](https://github.com/xlab-uiuc/acto/pull/257#issuecomment-1656657797) below
- [x] A bit docs are needed.

### CODE REVIEW

**Comment by tylergu** [comment]
@whentojump , does the profile have to be in the repo? I have experience of creating profiles from the CloudLab UI and the profile seems can be self-contained xml file.
I am referring to the `Upload files`, `Create topology` here.
image

Although I am not sure if these can be expressive enough

**Comment by whentojump** [comment]
Importing from a repository comes with a benefit that, the repository is automatically cloned at `/local/repository`. 

I'll try if there are issues with direct upload

**Comment by tylergu** [comment]
I see, I don't think that benefit is very necessary. Feel free to create a separate repo only containing the ansible script and the profile, we can just use that repo for bootstrap

**Comment by whentojump** [comment]
> Feel free to create a separate repo only containing the ansible script and the profile

Will do that

---

Regarding the second item of the task list

> It turns out the startup script is run by the nonhuman user `geniuser`. So the tmpfs and cloned acto repository are now in `/users/geniuser`.

Several workarounds I'm thinking of, from easy to hard:

1. Simply let reviewers run `sudo su - geniuser` at the very beginning
2. Create a neutral user like `acto-runner` in the script. Basically the same as 1 except a for different name
3. There're some hacks that can find out who is instantiating this particular run of the experiment.

    ```shell
    experiment_creator=$( geni-get user_urn | rev | cut -d '+' -f -1 | rev )
    ```

    We can then let an "outer" script (always called by `geni-user`) call an "inner" script on behalf of `$experiment_creator`.
    It magically works, just looks not so reliable...

4. I have been looking at [`geni-lib` docs](https://docs.cloudlab.us/geni-lib/index.html) to see if there's a way to learn the creator during Python execution but so far got no luck

I plan to work on 3. Any comments are appreciated! @tylergu

**Comment by whentojump** [comment]
I'm closing this PR because CloudLab- and Ansible-related stuffs are now here out-of-tree: https://github.com/xlab-uiuc/acto-cloudlab

@tylergu If you have time, can you walk it through and fit the content of that README into proper locations of `sosp-ae` branch? Thanks!

**Pull request closed without merging**
