### PR TITLE
Fix image preload

### PR DESCRIPTION
**Pull request by whentojump**
Still being tested. Details will follow once finalized.

For now please refer to https://uiuc-sysnet.slack.com/archives/C05ARSTLC6R/p1690248810330209?thread_ts=1690224327.936289&cid=C05ARSTLC6R

### CODE REVIEW

**Comment by tylergu** [comment]
@whentojump , this patch should fix the problem according to the experiment right?
Let's merge this one ASAP as it is a blocking fix

**Review by tylergu — APPROVED** [review]

**Comment by whentojump** [comment]
Test runs on RabbitMQ suggest the image preload is functioning (even though we're facing some new challenges now). 

I'll work on a brief description of the original problem at OP a bit later.

**Comment by whentojump** [comment]
Several updates:

> even though we're facing some new challenges now

This is resolved in PR 253, making us even more confident that this patch works!

> I'll work on a brief description of the original problem at OP a bit later.

Done.

**Comment by tianyin** [comment]
What's OP?

0_0

**Comment by whentojump** [comment]
There has been a countermeasure even before I joined, and this PR basically fixes several bugs in it. Most of the credit actually goes to Tyler.

> the rate limit is resolved

One particular test (with RabbitMQ) has been bothered by this issue. And recent runs with this patch can successfully complete.

> How likely we hit the rate limit again?

I'm actually still learning the internals and may need some sort of profiling to tell that. To my current understanding, this is determined by (1) how complicated the operator in question is, (2) how intensive we let each subtest run. I suppose we have got rid of most of unnecessarily duplicate pulls. If they exceed again in the future, in my opinion, this will pretty much become a devops thing (proxy, mirror sites, load balancing...) and not really our main concern in this project.

**Pull request merged**
