### PR TITLE
Input Model Refactor

### PR DESCRIPTION
**Pull request by MarkintoshZ**
PR for #296 

- [x] Schema matching based on Kubernetes OpenAPI specification
  - [x] Download OpenAPI specification by Kubernetes version
  - [x] Schema matching based on matching sub-properties
  - [x] Choosing the from multiple matching schema candidates based on edit distance between schema path suffix and schema name
  - [x]  Narrow down schemas candidates based on property names observed in OpenAPI Specification
  - [x] Test cases
- [ ] Generating test cases
  - [x] Implementing `generator` decorator
  - [ ] Refactor old testcase generation code to new design
  - [ ] Validating new system generates the same testcases as the old one
  - [ ] Port a few old operators to the new system

### CODE REVIEW

**Comment by tylergu** [comment]
I personally prefer the name "KubernetesMapSchema" and "KubernetesArraySchema" over "KubernetesDictSchema" and "KubernetesListSchema". As `Dict` and `List` are Python terms and `Array` is a JSON term.
Other than this, this patch looks great!

**Comment by tylergu** [comment]
@MarkintoshZ , just curious, does the dump_schema method guarantee to persist the original schema's constraints? Just looking at the ObjectSchema it seems it only handles the schemas for each subproperty

**Comment by MarkintoshZ** [comment]
@tylergu It does not currently. In my vision, the testcase generator functions would be provided with (if available) the matched k8s schema object, which stores the Kubernetes schema spec in the `schema_spec` attribute. So those constraints would be available when generating test cases. 

On second thought, do we still need to dump schema if each schema file is just part of the OpenAPI schema downloaded from Kubernetes' repo?

**Comment by MarkintoshZ** [comment]
Close this PR because it is broken into #307 and #311

**Pull request closed without merging**
